name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Install SQL Server
        uses: Particular/install-sql-server-action@main
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          catalog: nservicebus
      - name: Create schemas
        shell: pwsh
        run: |
            echo "Create additional schemas"
            sqlcmd -Q "CREATE SCHEMA receiver AUTHORIZATION db_owner" -d "nservicebus"
            sqlcmd -Q "CREATE SCHEMA sender AUTHORIZATION db_owner" -d "nservicebus"
            sqlcmd -Q "CREATE SCHEMA db@ AUTHORIZATION db_owner" -d "nservicebus"  
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore 
      - name: Test
        env: 
          ConnectionStrings_TestDatabase: server=localhost,1433;User=kura;Integrated Security=False;Password=W~08irasa
        run: dotnet test --no-build
