name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: W~08irasa
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Sleep for 5sec
      uses: jakejarvis/wait-action@master
      with: 
        time: '5s'    
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      env: 
        ConnectionStrings_TestDatabase: server=localhost; User ID = kura; Password=W~08irasa
      run: dotnet test --no-build
