name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SQL Server
        uses: Particular/install-sql-server-action@main
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          catalog: CiCd
      - name: Create schemas
        shell: pwsh
        run: |
            echo "Create additional schemas"
            sqlcmd -Q "CREATE SCHEMA receiver AUTHORIZATION db_owner" -d "CiCd"
            sqlcmd -Q "CREATE SCHEMA sender AUTHORIZATION db_owner" -d "CiCd"
            sqlcmd -Q "CREATE SCHEMA db@ AUTHORIZATION db_owner" -d "CiCd"
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Sleep for 5sec
        uses: jakejarvis/wait-action@master
        with: 
          time: '5s'    

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore 
      - name: Test
        env: 
          ConnectionStrings_TestDatabase: ${{env.SQL_SERVER_CONNECTION_STRING}}
        run: dotnet test --no-build
