name: .NET


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Start SQL Server
      run: |
        docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Pass~w0r8" -e "MSSQL_PID=Express" -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest    
    - name: Sleep for 5sec
      uses: jakejarvis/wait-action@master
      with: 
        time: '5s'    
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      env: 
        ConnectionStrings_DefaultConnection: Server=localhost;Database=NotesGit;User=sa;Password=Pass~w0r8
      run: dotnet test --no-build
